name: Docker

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/sbdb-auth:${{ github.sha }}
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sbdb-auth
